### ISSUE TITLE
[BUG] Fix bug with the ip_addresses test using wrong path

### ISSUE THREAD

**Issue by denverwilliams** [cnti-testcatalog/testsuite#1361] opened 2022-04-20 22:36 UTC
**Describe the bug**
The ip_addresses test currently only runs if the helm_chart_path argument is set. This argument is no longer used and the test needs to be updated to use the helm_directory, manifest_directory &  helm_chart arguments.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by horecoli** [comment] 2024-01-23 15:49
I tried to reproduce this bug, but I was not successful. I don't think this bug is relevant since this commit.: https://github.com/horecoli/cnf-testsuite/commit/2c06f66c1
@denverwilliams can you please confirm and close this bug?

**Comment by lixuna** [comment] 2024-02-06 18:33
Moving issue to Needs Peer Review - @denverwilliams @agentpoyo @HashNuke can this issue be closed?

**Comment by denverwilliams** [comment] 2024-02-13 22:46
@horecoli Closing as this bug is no longer relevant. 

This test was updated a while back to use the helm_chart_path argument. 
```./src/tasks/workload/configuration.cr:133: helm_chart_path = config.cnf_config[:helm_chart_path]```

This helm_chart_path argument gets the correct path by using: ```./src/tasks/utils/config.cr:150:      helm_chart_path = destination_cnf_dir + "/" + CNFManager.sandbox_helm_directory(working_chart_directory)```

So no changes will be needed for this test.

**Comment by denverwilliams** [comment] 2024-02-13 22:48
Test Run:
```
pair@cnfdev4:~/workspace/denver/testsuite$ ./cnf-testsuite -l info ip_addresses 
I, [2024-02-13 22:47:18 +00:00 #1297772]  INFO -- cnf-testsuite: Path: /home/pair/workspace/denver/testsuite/cnfs/coredns/exported_chart
I, [2024-02-13 22:47:18 +00:00 #1297772]  INFO -- cnf-testsuite-ip_addresses: current directory: /home/pair/workspace/denver/testsuite/cnfs/coredns/exported_chart
✔️  PASSED: No IP addresses found 📶🏃⏲️
I, [2024-02-13 22:47:18 +00:00 #1297772]  INFO -- cnf-testsuite: task_points: task: ip_addresses is worth: 0 points
I, [2024-02-13 22:47:18 +00:00 #1297772]  INFO -- cnf-testsuite: cmd: /home/pair/workspace/denver/testsuite/cnf-testsuite ip_addresses
I, [2024-02-13 22:47:18 +00:00 #1297772]  INFO -- cnf-testsuite-ip_addresses: task_runtime=12; start_time=2024-02-13 22:47:18 UTC; end_time:2024-02-13 22:47:18 UTC
I, [2024-02-13 22:47:18 +00:00 #1297772]  INFO -- cnf-testsuite: task_type_by_task
I, [2024-02-13 22:47:18 +00:00 #1297772]  INFO -- cnf-testsuite: points: {"name" => "ip_addresses", "pass" => 0, "fail" => -1, "tags" => "configuration, static, workload"}
I, [2024-02-13 22:47:18 +00:00 #1297772]  INFO -- cnf-testsuite: resp: ["configuration", "static", "workload"]
I, [2024-02-13 22:47:18 +00:00 #1297772]  INFO -- cnf-testsuite: task_type x: configuration acc: 
I, [2024-02-13 22:47:18 +00:00 #1297772]  INFO -- cnf-testsuite: task_type x: static acc: 
I, [2024-02-13 22:47:18 +00:00 #1297772]  INFO -- cnf-testsuite: task_type x: workload acc: 
I, [2024-02-13 22:47:18 +00:00 #1297772]  INFO -- cnf-testsuite: task_type: 
I, [2024-02-13 22:47:18 +00:00 #1297772]  INFO -- cnf-testsuite: upsert_task: task: ip_addresses has status: passed and is awarded: 0 points. Runtime: 12 seconds
I, [2024-02-13 22:47:18 +00:00 #1297772]  INFO -- cnf-testsuite: results yaml: {"name" => "cnf testsuite", "testsuite_version" => "main-2024-02-13-224718-7ef35e79", "status" => nil, "command" => "/home/pair/workspace/denver/testsuite/cnf-testsuite ip_addresses", "points" => nil, "exit_code" => 0, "items" => [{"name" => "ip_addresses", "status" => "passed", "type" => "", "points" => 0}]}

**Closed** 2024-02-13 22:49 UTC
Labels: bug, low
