### ISSUE TITLE
[Feature] Make cnf_cleanup deduce if the installation was a manifest installation

### ISSUE THREAD

**Issue by wavell** [cnti-testcatalog/testsuite#937] opened 2021-08-19 15:53 UTC
**Is your feature request related to a problem? Please describe.**
Make cnf_cleanup deduce if the installation was a manifest installation

**Describe the solution you'd like**
Make cnf_cleanup deduce if the installation was a manifest installation

**Comment by agentpoyo** [comment] 2021-08-19 16:51
This is a duplicate of https://github.com/cncf/cnf-testsuite/issues/935 @wavell

**Closed** 2024-02-28 17:01 UTC
Labels: duplicate
